name: Workflow Geçmişini Temizle (Private Repo 'Py' ile)

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Ana repo'yu çek
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Py repo'sunu klonla
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: requests kütüphanesini yükle
        run: pip install requests

      - name: Workflow geçmişini sil
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python private_py/delete_runs.py
